---
- hosts: 
  tasks:
      - name: Create .ssh directory if not exist
        file: 
          path: ~/.ssh 
          state: directory 
          owner: root
          mode: '0700' 
        tags:
          - directory

      - name: Create authorized_keys file if does not exist
        file:
          path: ~/.ssh/authorized_keys
          state: touch
          owner: root
          mode: '0644'
        tags:
          - authorized_keys

      - name: Add SSH Public Key
        blockinfile:
          path: ~/.ssh/authorized_keys
          block: put your public ssh key here
        tags:
          - key
