---
- hosts: all
  tasks:

  - lineinfile:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: '^TLSConnect '
      insertafter: '^#TLSConnect '
      line: 'TLSConnect=psk' 

  - blockinfile: |
      dest=/etc/zabbix/zabbix_agentd.conf
      content="PidFile=/var/run/zabbix/zabbix_agentd.pid
          LogFile=/var/log/zabbix/zabbix_agentd.log
          LogFileSize=0
          Server=your zabbix server
          ServerActive=your zabbix server
          Include=/etc/zabbix/zabbix_agentd.d/*.conf
          TLSConnect=psk
          TLSAccept=psk  
          TLSPSKIdentity=PSK 001
          TLSPSKFile=/etc/zabbix/zabbix_agentd.psk"
